#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RUN_LOCAL="$ROOT/scripts/linux/run_sift_local.sh"
INDEX_DIR="${INDEX_DIR:-$ROOT/build/sift_feature_indexes}"
BASE_LIMIT="${BASE_LIMIT:-100000}"
QUERY_LIMIT="${QUERY_LIMIT:-1000}"
SEARCH_WIDTH="${SEARCH_WIDTH:-256}"
SEARCH_EARLY_STOP_MIN="${SEARCH_EARLY_STOP_MIN:-96}"
RERANK_TOPK="${RERANK_TOPK:-64}"

mkdir -p "$INDEX_DIR"

run_profile() {
  local profile="$1"
  shift
  BASE_LIMIT="$BASE_LIMIT" QUERY_LIMIT="$QUERY_LIMIT" ENGINE=graph \
    DATASET_NAME="${DATASET_NAME:-sift_subset}" \
    SEARCH_WIDTH="$SEARCH_WIDTH" SEARCH_EARLY_STOP=1 \
    SEARCH_EARLY_STOP_MIN="$SEARCH_EARLY_STOP_MIN" \
    CACHE_POLICY=none PATH_CACHE_POLICY=none \
    DATE_TAG="feature-${profile}-$(date +%Y%m%d-%H%M%S)" \
    env "$@" bash "$RUN_LOCAL"
}

RAW_INDEX="$INDEX_DIR/sift-${BASE_LIMIT}-raw.idx"
HOTPATH_INDEX="$INDEX_DIR/sift-${BASE_LIMIT}-hotpath.idx"

run_profile raw INDEX="$RAW_INDEX" BUILD_INDEX=1 PACKING_STRATEGY=bfs
run_profile hotpath INDEX="$HOTPATH_INDEX" BUILD_INDEX=1 \
  PACKING_STRATEGY=hotpath HOTPATH_TRAIN_QUERIES="${HOTPATH_TRAIN_QUERIES:-200}"
run_profile adaptive INDEX="$RAW_INDEX" BUILD_INDEX=0 PACKING_STRATEGY=bfs \
  ADAPTIVE_EARLY_STOP=1 EARLY_STOP_PATIENCE="${EARLY_STOP_PATIENCE:-16}" \
  EARLY_STOP_EPS="${EARLY_STOP_EPS:-0.001}" \
  MIN_EXPANSIONS="${MIN_EXPANSIONS:-64}" MAX_EXPANSIONS="${MAX_EXPANSIONS:-192}"
run_profile pq-adc INDEX="$RAW_INDEX" BUILD_INDEX=0 PACKING_STRATEGY=bfs \
  PQ_ENABLE=1 ADC_ENABLE=1 PQ_M="${PQ_M:-8}" PQ_KS="${PQ_KS:-256}" \
  PQ_TRAIN_LIMIT="${PQ_TRAIN_LIMIT:-100000}" RERANK_TOPK=0
run_profile pq-adc-rerank INDEX="$RAW_INDEX" BUILD_INDEX=0 PACKING_STRATEGY=bfs \
  PQ_ENABLE=1 ADC_ENABLE=1 PQ_M="${PQ_M:-8}" PQ_KS="${PQ_KS:-256}" \
  PQ_TRAIN_LIMIT="${PQ_TRAIN_LIMIT:-100000}" RERANK_TOPK="$RERANK_TOPK"

python3 "$ROOT/scripts/linux/summarize_sift_results.py"
